import { useAppDispatch } from 'core';
import { client } from 'core/api/baseApi';
import { authSlice } from 'core/store/slice/Auth/slice';
import Head from 'next/head';
import styles from './mainLayout.module.scss';
export const MainLayout = ({ children }: { children: React.ReactNode }) => {
  const dispatch = useAppDispatch();
  return (
    <>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div
          className={styles.logout}
          onClick={() => {
            client.setHeader('authorization', '');
            localStorage.removeItem('token');
            dispatch(authSlice.actions.setToken({ token: null }));
          }}
        >
          LogOut
        </div>
        {children}
      </main>
    </>
  );
};
