import Head from 'next/head';
import styles from './../shared/styles/signIn.module.scss';
import { useState } from 'react';
import { SignInActions, SignInSelectors, useAppDispatch, useAppSelector } from 'core';
import { useQuery } from '@apollo/client';
import { FETCH_AUTH } from 'core/store/slice/Auth/queries';

export default function Home() {
  const userEmail = useAppSelector(SignInSelectors.signInEmailSelector);
  const dispatch = useAppDispatch();

  const { data, loading, error } = useQuery(FETCH_AUTH);
  console.log(data)

  const [inputData, setInputData] = useState({
    email: '',
    password: '',
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.signIn_wrapper}>
          <div className={styles.signIn_form}>
            {userEmail ? (
              <div>
                Hello, {userEmail}!
                <br />
                <button
                  onClick={() => {
                    dispatch(SignInActions.removeSignInDataAction());
                  }}
                >
                  Log out
                </button>
              </div>
            ) : (
              <>
                <h2>Sign In</h2>
                
                <input
                  className={styles.signIn_form__input}
                  value={inputData.email}
                  onChange={(e) =>
                    setInputData((prev) => ({
                      ...prev,
                      email: e.target.value,
                    }))
                  }
                  type="text"
                />

                <input
                  className={styles.signIn_form__input}
                  value={inputData.password}
                  onChange={(e) =>
                    setInputData((prev) => ({
                      ...prev,
                      password: e.target.value,
                    }))
                  }
                  type="password"
                />

                <button
                  onClick={() => {
                    dispatch(SignInActions.setSignInDataAction(inputData));
                    setInputData({
                      email: '',
                      password: '',
                    });
                  }}
                >
                  SignIn
                </button>
              </>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
